---
- hosts: localhost
  become: true
  tasks:
#    - name: Install required system packages
#      package:
#        name: "{{ item }}"
#        state: present
#      with_items:
#        - apt-transport-https
#        - software-properties-common

    - name: Add Grafana APT repository key
      apt_key:
        url: https://packages.grafana.com/gpg.key
        state: present

    - name: Add Grafana APT repository
      apt_repository:
        repo: deb https://packages.grafana.com/oss/deb stable main
        state: present
        update_cache: yes

    - name: Install Grafana
      apt:
        name: grafana
        state: present

    - name: Start and enable Grafana service
      service:
        name: grafana-server
        state: started
        enabled: yes

    - name: Add Prometheus APT repository key
      apt_key:
        url: https://packages.grafana.com/gpg.key
        state: present

    - name: Add Prometheus APT repository
      apt_repository:
        repo: deb https://packages.grafana.com/oss/deb stable main
        state: present
        update_cache: yes

    - name: Install Prometheus
      apt:
        name: prometheus
        state: present

    - name: Start and enable Prometheus service
      service:
        name: prometheus
        state: started
        enabled: yes